package com.university.service;

import com.university.model.*;
import com.university.repository.CourseOfferingRepository;
import com.university.repository.CourseRepository;
import com.university.repository.UserRepository;

import java.util.ArrayList;
import java.util.List;

public class AdminService {
    private CourseRepository courseRepository;
    private CourseOfferingRepository offeringRepository;
    private UserRepository userRepository; // NEW

    // Updated Constructor
    public AdminService(CourseRepository courseRepository, CourseOfferingRepository offeringRepository,
            UserRepository userRepository) {
        this.courseRepository = courseRepository;
        this.offeringRepository = offeringRepository;
        this.userRepository = userRepository;
    }

    // --- Base Course Methods ---
    public List<Course> getAllCourses() {
        return courseRepository.findAll();
    }

    public boolean createNewCourse(String code, String title, int credits) {
        if (courseRepository.findByCode(code) != null) {
            return false;
        }
        Course newCourse = new Course(code, title, credits);
        courseRepository.save(newCourse);
        return true;
    }

    // --- Course Offering Methods ---
    public List<CourseOffering> getAllOfferings() {
        return offeringRepository.findAll();
    }

    // Inside AdminService.java
    public boolean createCourseOffering(String courseCode, String semester, int capacity, TimeSlot timeSlot,
            String professorId) {
        Course baseCourse = courseRepository.findByCode(courseCode);
        if (baseCourse == null)
            return false;

        int sectionNumber = 1;
        for (CourseOffering existing : offeringRepository.findAll()) {
            if (existing.getCourse().getCourseCode().equals(courseCode) && existing.getSemester().equals(semester)) {
                sectionNumber++;
            }
        }

        String cleanSemester = semester.replaceAll("\\s+", "");
        String autoGeneratedId = String.format("%s-%s-%02d", courseCode, cleanSemester, sectionNumber);

        // Include the time slot in creation
        CourseOffering newOffering = new CourseOffering(autoGeneratedId, baseCourse, semester, capacity, timeSlot);

        // If a professor was selected, assign them immediately!
        if (professorId != null && !professorId.equals("UNASSIGNED")) {
            User prof = userRepository.findByUsername(professorId);
            if (prof instanceof Professor) {
                ((Professor) prof).addCuratedCourse(newOffering);
            }
        }

        offeringRepository.save(newOffering);
        return true;
    }

    public boolean createUser(String role, String id, String name) {
        if (userRepository.findByUsername(id) != null) {
            return false; // Username/ID already exists
        }

        User newUser;
        if (role.equals("PROFESSOR")) {
            newUser = new Professor(id, id, name);
        } else if (role.equals("STUDENT")) {
            newUser = new Student(id, id, name);
        } else {
            return false;
        }

        userRepository.save(newUser);
        return true;
    }

    public List<User> getAllUsers() {
        return userRepository.findAll();
    }

    public List<Professor> getAllProfessors() {
        List<Professor> professors = new ArrayList<>();
        for (User u : userRepository.findAll()) {
            if (u instanceof Professor) {
                professors.add((Professor) u);
            }
        }
        return professors;
    }

    // --- NEW: Assigning Professors ---
    public boolean assignProfessorToOffering(String offeringId, String professorId) {
        CourseOffering offering = offeringRepository.findById(offeringId);
        User user = userRepository.findByUsername(professorId);

        if (offering != null && user != null && user instanceof Professor) {
            Professor prof = (Professor) user;
            prof.addCuratedCourse(offering); // This links both sides!
            return true;
        }
        return false;
    }

    public boolean modifyOfferingSchedule(String offeringId, TimeSlot newTimeSlot) {
        CourseOffering offering = offeringRepository.findById(offeringId);
        if (offering == null) {
            return false;
        }

        offering.setTimeSlot(newTimeSlot);
        offeringRepository.save(offering); // Save the updated offering back to the repository
        return true;
    }

    public boolean addPrerequisite(String mainCourseCode, String prereqCourseCode) {
        Course mainCourse = courseRepository.findByCode(mainCourseCode);
        if (mainCourse == null)
            return false;

        // --- NEW: Handle the "NONE" clear command ---
        if (prereqCourseCode.equals("NONE")) {
            mainCourse.getPrerequisites().clear(); // Empties the list
            return true;
        }

        // Prevent a course from being its own prerequisite
        if (mainCourseCode.equals(prereqCourseCode)) {
            return false;
        }

        Course prereqCourse = courseRepository.findByCode(prereqCourseCode);
        if (prereqCourse != null) {
            mainCourse.addPrerequisite(prereqCourse); // Adds to the existing list
            return true;
        }

        return false;
    }
}